### ISSUE TITLE
It does not deploy properly cloudflare

### ISSUE THREAD

**Issue by bestruirui** [K0IN/Notify#67]
wrangler.toml Updates required
npm run build_all error
```
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 Build  [==                  ] 10% (0.0s) buildingError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/workspaces/empty/Notify/app/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /workspaces/empty/Notify/app/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/workspaces/empty/Notify/app/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /workspaces/empty/Notify/app/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
 Build  [==                  ] 10% (0.3s) building✖ ERROR Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/empty/Notify/app/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/workspaces/empty/Notify/app/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /workspaces/empty/Notify/app/frontend/node_modules/babel-loader/lib/index.js:59:71
```

**Comment by bestruirui** [comment]
![image](https://user-images.githubusercontent.com/89796393/232042311-2c305042-1d6e-4536-967d-b33ab273e72b.png)

**Comment by bestruirui** [comment]
![image](https://user-images.githubusercontent.com/89796393/232048124-426cb51a-2170-4ab1-b409-d37fa8d5ab49.png)

**Comment by K0IN** [comment]
I'm a bit busy right now, i think this might be an incompatible node version can you try node 16?

I will try to come back to you asap.

**Comment by bestruirui** [comment]
Thank you for your reply
I've used node16
Compiles successfully but cannot be deployed to Cloudflare

**Comment by K0IN** [comment]
have you set the environment variables correctyly?
Did you see this guide https://github.com/K0IN/Notify/blob/main/doc/install/cloudflare.md
